### ISSUE TITLE
好大一条bug

### ISSUE THREAD

**Issue by Sidnio** [yixiaolunhui/FSearchHistory#1]
![image](https://user-images.githubusercontent.com/33193340/135566322-55d742b1-ffc4-42b0-8875-99e1ef98e363.png)
加载数据 箭头不见了

**Comment by yixiaolunhui** [comment]
请问你的数据总共超过了2行了吗，如果你数据不超过你设定的折叠行数时是不显示的 折行（箭头）的

**Comment by yixiaolunhui** [comment]
> ![image](https://user-images.githubusercontent.com/33193340/135566322-55d742b1-ffc4-42b0-8875-99e1ef98e363.png)
> 加载数据 箭头不见了

请问你的数据总共超过了2行了吗，如果你数据不超过你设定的折叠行数时是不显示的 折行（箭头）的

**Comment by yixiaolunhui** [comment]
> ![image](https://user-images.githubusercontent.com/33193340/135566322-55d742b1-ffc4-42b0-8875-99e1ef98e363.png)
> 加载数据 箭头不见了

请问你的数据总共超过了2行了吗，如果你数据不超过你设定的折叠行数时是不显示的 折行（箭头）的

**Comment by Sidnio** [comment]
超过 两行了

加载数据 新的数据进来所有view都会清除
![image](https://user-images.githubusercontent.com/33193340/135601501-b6fd0621-4f2b-4c80-8cb7-ed054ee1710a.png)


这里刚好是折叠转态
![image](https://user-images.githubusercontent.com/33193340/135601618-8ec49b5e-47df-4c41-83c1-7cede4ff09eb.png)

 Timber.v("刷新布局 第 %s 次  为 %s      是否折叠  %s", ++a ,newFoldState,mFoldState);
![image](https://user-images.githubusercontent.com/33193340/135601817-e6dd076c-a535-4ac4-a2c7-4b5ff389c2e8.png)

无法回调  
![image](https://user-images.githubusercontent.com/33193340/135602126-d07ccddc-48c9-4cdf-a9cc-1d54eace9544.png)



导致原因是 不可见 变可见 刷新数据 导致,   


刷新数据也会 看不见

**Comment by Sidnio** [comment]
![GIF3](https://user-images.githubusercontent.com/33193340/135603143-835375f9-6e71-4a94-bda8-8050c6f41f33.gif)


注意观察箭头

**Comment by yangqian923424** [comment]
> ![GIF3](https://user-images.githubusercontent.com/33193340/135603143-835375f9-6e71-4a94-bda8-8050c6f41f33.gif)
> 
> 注意观察箭头

好多BUG，哈哈。动态添加数据超过两行不显示折叠箭头，重新设置数据不显示箭头，初始化偶尔不显示箭头

**Comment by billdizl** [comment]
跑路了  不用再提iss

**Comment by yixiaolunhui** [comment]
> 跑路了 不用再提iss

已修复，不好意思，给你带来不便了

**Comment by yixiaolunhui** [comment]
> > ![GIF3](https://user-images.githubusercontent.com/33193340/135603143-835375f9-6e71-4a94-bda8-8050c6f41f33.gif)
> >       
> >         [
> >           
> >         
> >             ![GIF3](https://user-images.githubusercontent.com/33193340/135603143-835375f9-6e71-4a94-bda8-8050c6f41f33.gif)
> >           ](https://user-images.githubusercontent.com/33193340/135603143-835375f9-6e71-4a94-bda8-8050c6f41f33.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/33193340/135603143-835375f9-6e71-4a94-bda8-8050c6f41f33.gif)
> >         
> >       
> > 注意观察箭头
> 
> 好多BUG，哈哈。动态添加数据超过两行不显示折叠箭头，重新设置数据不显示箭头，初始化偶尔不显示箭头

已修复，不好意思，给你带来不便了

**Comment by yixiaolunhui** [comment]
> ![GIF3](https://user-images.githubusercontent.com/33193340/135603143-835375f9-6e71-4a94-bda8-8050c6f41f33.gif) [ ![GIF3](https://user-images.githubusercontent.com/33193340/135603143-835375f9-6e71-4a94-bda8-8050c6f41f33.gif) ](https://user-images.githubusercontent.com/33193340/135603143-835375f9-6e71-4a94-bda8-8050c6f41f33.gif) [ ](https://user-images.githubusercontent.com/33193340/135603143-835375f9-6e71-4a94-bda8-8050c6f41f33.gif)
> 
> 注意观察箭头

已修复，不好意思，给你带来不便了
