### ISSUE TITLE
find bugs

### ISSUE THREAD

**Issue by nicoleyip** [yixiaolunhui/FSearchHistory#2]
Hi, there is a bug in below class
https://github.com/yixiaolunhui/FSearchHistory/blob/e0d2a37bd59cf9e5d9bb63745a727b4e6b3e03f1/app/src/main/java/com/yxlh/fsearchhistory/jd/JDFoldLayout.java#L86

bug: repeat get child at same index
fix: `View view = getChildAt(i);`

Best regards :)

**Comment by yixiaolunhui** [comment]
谢谢指出，三克油
